<template>
  <div class="about">

    <div class="stats" v-show="answered.length < num_articles">
      <div class="position-absolute" style="top:-4.7em; left:0">
        <h3 class="m-3">
          {{ answered.length + 1 }} / {{ num_articles }}
        </h3>
      </div>
      <div class="position-absolute" style="top:-4.7em; right:0">
        <h3 class="m-3">{{ score }}</h3>
      </div>
    </div>

    <h1 class="pt-4 serif font-weight-bold">{{ $t('title') }}</h1>
    <h5 class="pb-4">Can you tell which articles have been generated by artificial
    intelligence and which ones were actually printed in newspapers?</h5>

    <b-alert :show="answered.length === num_articles" fade>
      <h4 class="alert-heading stats">Well done!</h4>
      <hr>
      <p class="stats" v-html=this.alertMessage></p>
      <b-button @click="resetGame()" variant="outline-info">Play again !</b-button>
    </b-alert>

    <div class="controls-container">
      <b-button-group class="w-100">
        <b-button variant="outline-danger" @click="checkNews(false)"
        :disabled="disableButtons">
          <b-icon icon="chevron-left"></b-icon> &nbsp; &nbsp; Fake
        </b-button>
        <b-button variant="outline-secondary" @click="checkNews()">
          Pass
        </b-button>
        <b-button variant="outline-success" @click="checkNews(true)"
        :disabled="disableButtons">
          Fact &nbsp; &nbsp; <b-icon icon="chevron-right"></b-icon>
        </b-button>
      </b-button-group>
    </div>

    <div v-show="answered.length < num_articles">

      <div class="app-container">

        <div class="articles-container">
          <div class="article">
            <div class="date">
              {{ $d(new Date(current_article.date), 'long') }}
            </div>
            <h3 class="title serif font-weight-bold">
              {{ current_article.title }}
            </h3>
            <div class="excerpt serif">
              {{ current_article.excerpt }}
            </div>
          </div>
        </div>

        <transition name="fadescale"
          v-on:after-enter="showFeedback = {}" v-on:after-leave="shuffleArticles">
          <div class="checkit success" v-show="showFeedback.success">
            <b-icon icon="check-circle" font-scale="5"></b-icon>
          </div>
        </transition>
        <transition name="fadescale"
          v-on:after-enter="showFeedback = {}" v-on:after-leave="shuffleArticles">
          <div class="checkit fail" v-show="showFeedback.fail">
            <b-icon icon="x-circle" font-scale="5"></b-icon>
          </div>
        </transition>
      </div>
    </div>
  </div>
</template>

<script>

import json from '../data/news.json';

export default {
  data: () => ({
    articles: json.articles,
    score: 0,
    correctAnswers: 0,
    rand: 0,
    answered: [],
    showFeedback: {},
    disableButtons: false,
    alertMessage: '',
  }),
  created() {
    this.shuffleArticles();
  },
  computed: {
    num_articles() {
      return this.articles.length;
    },
    current_article() {
      return this.articles[this.rand];
    },
  },
  methods: {
    track(correctAnswer) {
      this.$gtag.event('answer', {
        event_category: correctAnswer ? 'correct' : 'wrong',
        event_label: this.current_article.title,
        value: +correctAnswer,
      });
      // console.log(+correctAnswer);
    },
    shuffleArticles() {
      if (this.answered.length >= this.num_articles) {
        this.alertMessage = `You guessed ${this.correctAnswers} out of ${this.num_articles} articles correctly.<br>Your score: ${this.score}`;
      } else {
        this.rand = Math.floor(Math.random() * this.num_articles);
        while (this.answered.includes(this.rand)) {
          this.rand = Math.floor(Math.random() * this.num_articles);
        }
      }
      this.disableButtons = false;
    },
    resetGame() {
      this.answered = [];
      this.correctAnswers = 0;
      this.alertMessage = '';
      this.score = 0;
    },
    checkNews(answer) {
      // console.log(answer, this.articles[this.current_article].isFake);
      if (typeof answer === 'undefined') {
        this.shuffleArticles();
      } else {
        this.disableButtons = true;
        this.track(answer !== this.current_article.isFake);
        if (answer === this.current_article.isFake) {
          this.showFeedback.fail = true;
          // this.score -= 5;
        } else {
          this.showFeedback.success = true;
          this.score += 1000;
          this.correctAnswers += 1;
        }
        this.answered.push(this.rand);
      }
    },
  },
};

</script>

<style lang="scss" media="screen">
  .about {
    position: relative;
    padding: 0 1em;
    max-width: 48rem;
    margin: auto;
  }
  .stats {
    font-family: Dosis;
  }
  .btn:not(:hover) {
    background-color: white;
  }
  .app-container {
    position: relative;
    border: 2px solid #white;
    .articles-container {
      background: url(../assets/newspaper-clipping.gif);
      background-repeat: no-repeat;
      background-position: top center;
      background-size: 100vmin;
      margin-left: -26vmin;
      margin-right: -26vmin;
      height: 120vmin;
      max-height: 104vmin;
      // border: 1px solid red;
      .article {
        width: 72vmin;
        // max-width: 32rem;
        height: 73vmin;
        // max-height: 30rem;
        color: rgb(110,100,90); // rgb(53,46,49);
        margin: 0 auto;
        overflow: hidden;
        transform: rotate(-0.8deg);
        mix-blend-mode: multiply;
        padding-left: calc( 10px + 0.8vmin);
        // border: 1px dotted red;
      }
      .date {
        padding-top: 11vmin;
        padding-bottom: 2vmin;
        text-transform: uppercase;
        letter-spacing: 0.2em;
        font-size: 1.3vmin;
        font-weight: bold;
        // border: 1px solid blue
      }
      .title {
        padding: 1.5vmin 0;
        // max-width: 28rem;
        font-size: 4.5vmin;
        border-bottom: 1.5px solid rgba(110,100,90,.8);
      }
      .excerpt {
        columns: 2;
        column-gap: 2.5vmin;
        column-rule: 1px solid rgba(110,100,90,.8);
        text-align: left;
        font-size: 2.35vmin;
        // border: 1px dotted green;
        // height: 100%;
        // line-height: 1.4em;
      }
    }
    .checkit {
      position: absolute;
      width: 100%;
      top: 35vmin;
      left: 0;
      margin: 0 auto;
      &.success {
        color: #42b983;
      }
      &.fail {
        color: red;
      }
    }
  }
  .fadescale-enter-active {
    transition: all .2s ease-out;
  }
  .fadescale-leave-active {
    transition: all .8s ease-in;
  }
  .fadescale-enter-to {
    transform: scale(2.2);
    // transform: translateY(-20px);
  }
  .fadescale-leave-to {
    // transform: translateY(-60px);
    transform: scale(0.2);
    opacity: 0;
  }
</style>

<i18n>
{
  "en": {
    "title": "Fact or Fake ?"
  }
}
</i18n>
